"""Experiments Config 
"""
ALGORITHM = "bounded_coordinate_hessian"
DIMENSIONALITY = 2
THETA_NORM = 2
EXPERT_SCALE = 1
X_MIN = -3
X_MAX = 3
GRID_RES = 70j
PRIOR_VARIANCE_SCALE = 1
PLOT = False
SEED = 10
SIMULATION_STEPS = 1000
